# Generated by Django 3.1.5 on 2021-01-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_question', models.CharField(max_length=40)),
                ('Question_enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=30)),
                ('User_password', models.CharField(max_length=200)),
                ('User_enable', models.BooleanField(blank=True)),
                ('User_answer', models.TextField()),
                ('User_ff', models.TextField()),
            ],
        ),
    ]
