# Generated by Django 3.1.5 on 2021-01-16 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctpwebsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='User_ff',
        ),
    ]
