# Generated by Django 3.1.5 on 2021-01-16 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctpwebsite', '0003_auto_20210116_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='User_Questionid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ctpwebsite.question'),
        ),
    ]
