# Generated by Django 3.1.5 on 2021-01-16 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctpwebsite', '0004_users_user_questionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='User_Questionid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='ctpwebsite.question'),
        ),
    ]
