# Generated by Django 3.1.5 on 2021-01-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctpwebsite', '0007_auto_20210118_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='User_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='账号'),
        ),
    ]
