# Generated by Django 3.1.5 on 2021-01-20 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctpwebsite', '0008_auto_20210118_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='Question',
        ),
        migrations.AddField(
            model_name='users',
            name='question',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='ctpwebsite.question', verbose_name='验证问题ID'),
        ),
    ]
